[package]
name = "mindgrove-rtos"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = "0.16.0"
riscv-rt = "0.17.0"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
