[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -nographic -bios none -kernel"
rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
]
 
[build]
target = "riscv64imac-unknown-none-elf"